[package]
name = "hs-grpc-shared"
version = "0.1.0"
edition = "2021"


[dependencies]
prost = { workspace = true }
candle-core = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
